feat: overhaul of script echo output

diff --git a/scripts/add-environments-to-project b/scripts/add-environments-to-project
--- a/scripts/add-environments-to-project
+++ b/scripts/add-environments-to-project
@@ -1,27 +1,50 @@
 #!/bin/bash
 
+Color_Off='\033[0m'       # Text Reset
+# Regular Colors
+Red='\033[0;31m'          # Red
+Green='\033[0;32m'        # Green
+Blue='\033[0;34m'         # Blue
+Yellow='\033[0;33m'       # Yellow
+Purple='\033[0;35m'       # Purple
+
+remove="${Purple}DELETE${Color_Off}"
+success="${Green}SUCCESS${Color_Off}"
+create="${Green}CREATE${Color_Off}"
+update="${Green}UPDATE${Color_Off}"
+error="${Red}ERROR${Color_Off}"
+starting="${Yellow}STARTING${Color_Off}"
+line="${Yellow}#################################${Color_Off}"
+complete="${Yellow}COMPLETED${Color_Off}"
+
 empty="empty"
-project=$empty
+name=$empty
 basePath="/workspace"
-success="SUCCESS"
-error="ERROR"
-starting="STARTING"
+
+command_msg(){
+  if [ $? == 0 ] ; then
+    echo -e "$1 $2"
+  else
+    echo -e "$error $2"
+    exit 1
+  fi
+}
 
 # display help message if -h is a commandline arg
 help_message() {
   if [[ $1 == "-h" ]]; then
-    echo "Usage add-environments.sh -p {project name}";
+    echo "Usage add-environments-to-project.sh -n {project-name}";
     echo "-n: Angular project to add environments to";
     echo "OPTIONS:"
     echo "-b Root of the angular mono-repo"
-    exit 0
+    exit 1
   fi
 }
 
 while getopts n:b:h flag
 do
     case "${flag}" in
-        n) project=${OPTARG};;
+        n) name=${OPTARG};;
         b) basePath=${OPTARG};;
         h) help="-h";;
     esac
@@ -30,30 +53,33 @@ done
 # display help message if -h is a commandline arg
 help_message $help
 
-echo "#################################"
-echo "$starting: Adding environments to project $name"
-echo "#################################"
+echo -e $line
+echo -e "$starting Adding environments to project $name"
 
 if [[ ! -d $basePath ]]; then
-  echo "$error: Root of the angular mono-repo cannot be found ($basePath)"
-  exit 0
+  echo -e "$error Root of the angular mono-repo cannot be found ($basePath)"
+  exit 1
 fi
 
 cd $basePath
 
-projectPath="./projects/$project/src";
+projectPath="./projects/$name/src";
 
 # if the project has been successfully created lets customise it
 if [[ ! -f "$projectPath/app/app.module.ts" ]]; then
-  echo "$error: Project $name could not be found";
-  exit 0;
+  echo -e "$error Project $name could not be found";
+  exit 1;
 fi
 
 # added environment variables
 cp -a ./templates/environments $projectPath
-echo "$success: environments copied to project"
+command_msg $success "environments copied to project $name"
+
 # update angular.json with production fileReplacements for env
-updatedAngularJson="$(jq ".projects.$project.architect.build.configurations.production.fileReplacements += [{\"replace\": \"projects/$project/src/environments/environment.ts\",\"with\": \"projects/$project/src/environments/environment.prod.ts\"}]" ./angular.json)"
+updatedAngularJson="$(jq ".projects.$name.architect.build.configurations.production.fileReplacements += [{\"replace\": \"projects/$name/src/environments/environment.ts\",\"with\": \"projects/$name/src/environments/environment.prod.ts\"}]" ./angular.json)"
 echo -E "${updatedAngularJson}" > angular.json
-echo "$success: angular.json updated with production.fileReplacements for environments"
+command_msg $update "angular.json"
+
+echo -e "$success Environments added to project $name"
+echo -e $line
 
diff --git a/scripts/add-formly-to-project b/scripts/add-formly-to-project
--- a/scripts/add-formly-to-project
+++ b/scripts/add-formly-to-project
@@ -1,28 +1,51 @@
 #!/bin/bash
 
+Color_Off='\033[0m'       # Text Reset
+# Regular Colors
+Red='\033[0;31m'          # Red
+Green='\033[0;32m'        # Green
+Blue='\033[0;34m'         # Blue
+Yellow='\033[0;33m'       # Yellow
+Purple='\033[0;35m'       # Purple
+
+remove="${Purple}DELETE${Color_Off}"
+success="${Green}SUCCESS${Color_Off}"
+create="${Green}CREATE${Color_Off}"
+update="${Green}UPDATE${Color_Off}"
+error="${Red}ERROR${Color_Off}"
+starting="${Yellow}STARTING${Color_Off}"
+line="${Yellow}#################################${Color_Off}"
+complete="${Yellow}COMPLETED${Color_Off}"
+
 empty="empty"
 name=$empty
 install="n"
 basePath="/workspace"
-success="SUCCESS"
-error="ERROR"
-starting="STARTING"
+
+command_msg(){
+  if [ $? == 0 ] ; then
+    echo -e "$1 $2"
+  else
+    echo -e "$error $2"
+    exit 1
+  fi
+}
 
 help_message() {
   if [[ $1 == "-h" ]]; then
-    echo "Usage new_mfe.sh -p {dev port} -n {project name} [options]";
+    echo "Usage add-formly-to-project.sh -n {project name} [options]";
     echo "-n: Project name"
     echo "OPTIONS:"
     echo "-i: install formly into workspace (n)";
     echo "-b Root of the angular mono-repo"
-    exit 0
+    exit 1
   fi
 }
 
 validate_args() {
   if [[ $name == $empty ]] ; then
-    echo "$error: Invalid arguments, please see help (-h)"
-    exit 0
+    echo -e "$error Invalid arguments, please see help (-h)"
+    exit 1
   fi
 }
 
@@ -40,9 +63,8 @@ done
 help_message $help
 validate_args
 
-echo "#################################"
-echo "$starting: Adding Formly to Project $name"
-echo "#################################"
+echo -e $line
+echo -e "$starting Adding Formly to Project $name"
 
 cd $basePath
 projectPath="./projects/$name/src";
@@ -50,23 +72,38 @@ appPath="$projectPath/app"
 
 if [[ $install == "y" || $install == "Y" ]]; then
     ng add @ngx-formly/schematics --ui-theme=material --project $name
-    echo "$success: Formly added"
+    echo -e "$success Formly added"
 fi
 mkdir -p $appPath/pages/basic-form-page/
 cp -r $basePath/templates/basic-form-page/* $appPath/pages/basic-form-page/
+command_msg $success "Formly basic page copy"
 cp $appPath/pages/basic-form-page/basic-form-page.component.spec.ts.txt $appPath/pages/basic-form-page/basic-form-page.component.spec.ts
+command_msg $create "$appPath/pages/basic-form-page/basic-form-page.component.spec.ts"
 rm $appPath/pages/basic-form-page/basic-form-page.component.spec.ts.txt
+command_msg $remove "$appPath/pages/basic-form-page/basic-form-page.component.spec.ts.txt"
 cp $appPath/pages/basic-form-page/basic-form-page.component.ts.txt $appPath/pages/basic-form-page/basic-form-page.component.ts
+command_msg $create "$appPath/pages/basic-form-page/basic-form-page.component.ts"
 rm $appPath/pages/basic-form-page/basic-form-page.component.ts.txt
+command_msg $remove "$appPath/pages/basic-form-page/basic-form-page.component.ts.txt"
 
 
 sed -i "s/{ ReactiveFormsModule }/{ FormsModule, ReactiveFormsModule }/g" $appPath/app.module.ts
+command_msg $update "$appPath/app.module.ts"
 sed -i "/^@NgModule.*/i import { BasicFormPageComponent } from './pages/basic-form-page/basic-form-page.component';" $appPath/app.module.ts
+command_msg $update "$appPath/app.module.ts"
 
 sed -i "/imports.*/a FormsModule," $appPath/app.module.ts
+command_msg $update "$appPath/app.module.ts"
 sed -i "/declarations.*/a BasicFormPageComponent," $appPath/app.module.ts
+command_msg $update "$appPath/app.module.ts"
 
 sed -i "/^export const APP_ROUTES: Routes.*/i import { BasicFormPageComponent } from '../pages/basic-form-page/basic-form-page.component';" $appPath/router/app.routes.ts
+command_msg $update "$appPath/router/app.routes.ts"
 sed -i "/^export const APP_ROUTES: Routes.*/a { path: 'basic-form', component: BasicFormPageComponent,}," $appPath/router/app.routes.ts
+command_msg $update "$appPath/router/app.routes.ts"
 
 echo '<div><a routerLink="/basic-form">Basic Form</a></div>' >> $appPath/pages/landing-page/landing-page.component.html
+command_msg $update "$appPath/pages/landing-page/landing-page.component.html"
+
+echo -e "$success Formly added to Project $name"
+echo -e $line
diff --git a/scripts/add-gl-to-project b/scripts/add-gl-to-project
--- a/scripts/add-gl-to-project
+++ b/scripts/add-gl-to-project
@@ -1,36 +1,70 @@
+#!/bin/bash
+
+Color_Off='\033[0m'       # Text Reset
+# Regular Colors
+Red='\033[0;31m'          # Red
+Green='\033[0;32m'        # Green
+Blue='\033[0;34m'         # Blue
+Yellow='\033[0;33m'       # Yellow
+Purple='\033[0;35m'       # Purple
+
+remove="${Purple}DELETE${Color_Off}"
+success="${Green}SUCCESS${Color_Off}"
+create="${Green}CREATE${Color_Off}"
+update="${Green}UPDATE${Color_Off}"
+error="${Red}ERROR${Color_Off}"
+starting="${Yellow}STARTING${Color_Off}"
+line="${Yellow}#################################${Color_Off}"
+complete="${Yellow}COMPLETED${Color_Off}"
+
 empty="empty"
 name=$empty
 install="n"
 workspace=$empty
+mfeType=$empty
 basePath="/workspace"
-success="SUCCESS"
-error="ERROR"
-starting="STARTING"
+
+command_msg(){
+  if [ $? == 0 ] ; then
+    echo -e "$1 $2"
+  else
+    echo -e "$error $2"
+    exit 1
+  fi
+}
 
 help_message() {
   if [[ $1 == "-h" ]]; then
-    echo "Usage new_mfe.sh -p {dev port} -n {project name} [options]";
+    echo "Usage add-gl-to-project.sh -n {project name} -w {workspace} [options]";
     echo "-n: Project name"
-    echo "-w: Angular workspace name";
+    echo "-w: Angular workspace name workspace - hint: look at your lib {workspace}-lib";
+    echo "-t: MFE type s (shell) or r (remote)"
     echo "OPTIONS:"
     echo "-i: install golden-layout (n)"
     echo "-b Root of the angular mono-repo"
-    exit 0
+    exit 1
   fi
 }
 
 validate_args() {
-  if [[ $name == $empty || $workspace == $empty ]] ; then
-    echo "$error: Invalid arguments, please see help (-h)"
-    exit 0
+
+  if [[ $name == $empty || $workspace == $empty || $mfeType == $empty ]] ; then
+    echo -e "$error Invalid arguments, please see help (-h)"
+    echo "name: $name"
+    echo "workspace: $workspace"
+    echo "mfeType: $mfeType"
+    echo "---------------------------------"
+    help_message "-h"
+    exit 1
   fi
 }
 
-while getopts n:w:i:b:h flag
+while getopts n:w:t:i:b:h flag
 do
     case "${flag}" in
         n) name=${OPTARG};;
         w) workspace=${OPTARG};;
+        t) mfeType=${OPTARG};;
         b) basePath=${OPTARG};;
         i) install=${OPTARG};;
         h) help="-h";;
@@ -42,9 +76,8 @@ help_message $help
 
 validate_args
 
-echo "#################################"
-echo "$starting: Adding Golden Layout to project $name"
-echo "#################################"
+echo -e $line
+echo -e "$starting Adding Golden Layout to project $name"
 
 cd $basePath
 projectPath="./projects/$name/src";
@@ -52,56 +85,92 @@ appPath="$projectPath/app"
 
 if [[ $install == "y" || $install == "Y" ]]; then
     npm install golden-layout --save
-    echo "$success: Golden layout installed"
+    command_msg $success "Golden layout installed"
 fi
 
 mkdir -p $appPath/components/golden-layout
 cp -r $basePath/templates/golden-layout/* $appPath/components/golden-layout/
+command_msg $success "Golden layout templates added to project $name"
 
 sed -i "s/{workspace}/$workspace/g" $appPath/components/golden-layout/golden-layout-component.service.ts
+command_msg $update "$appPath/components/golden-layout/golden-layout-component.service.ts"
+
 sed -i "s/{workspace}/$workspace/g" $appPath/components/golden-layout/boolean/boolean.component.ts
+command_msg $update "$appPath/components/golden-layout/boolean/boolean.component.ts"
+
 sed -i "s/{workspace}/$workspace/g" $appPath/components/golden-layout/text/text.component.ts
+command_msg $update "$appPath/components/golden-layout/text/text.component.ts"
+
 sed -i "s/{workspace}/$workspace/g" $appPath/components/golden-layout/color/color.component.ts
+command_msg $update "$appPath/components/golden-layout/color/color.component.ts"
+
 sed -i "s/{workspace}/$workspace/g" $appPath/components/golden-layout/controls/controls.component.ts
+command_msg $update "$appPath/components/golden-layout/controls/controls.component.ts"
+
 sed -i "s/{workspace}/$workspace/g" $appPath/components/golden-layout/golden-layout-host/golden-layout-host.component.ts
+command_msg $update "$appPath/components/golden-layout/golden-layout-host/golden-layout-host.component.ts"
 
 mkdir -p $appPath/pages/golden-layout-example-page/
 cp -r $basePath/templates/golden-layout-example-page/* $appPath/pages/golden-layout-example-page/
+command_msg $success "Golden Layout example page copy"
+
 cp $appPath/pages/golden-layout-example-page/golden-layout-example-page.component.spec.ts.txt $appPath/pages/golden-layout-example-page/golden-layout-example-page.component.spec.ts
+command_msg $create "$appPath/pages/golden-layout-example-page/golden-layout-example-page.component.spec.ts"
+
 rm $appPath/pages/golden-layout-example-page/golden-layout-example-page.component.spec.ts.txt
+command_msg $remove "$appPath/pages/golden-layout-example-page/golden-layout-example-page.component.spec.ts.txt"
+
 cp $appPath/pages/golden-layout-example-page/golden-layout-example-page.component.ts.txt $appPath/pages/golden-layout-example-page/golden-layout-example-page.component.ts
+command_msg $create "$appPath/pages/golden-layout-example-page/golden-layout-example-page.component.ts"
+
 rm $appPath/pages/golden-layout-example-page/golden-layout-example-page.component.ts.txt
+command_msg $remove "$appPath/pages/golden-layout-example-page/golden-layout-example-page.component.ts.txt"
 
 sed -i "/export const APP_ROUTES: Routes.*/i import { GoldenLayoutExamplePageComponent } from '../pages/golden-layout-example-page/golden-layout-example-page.component';" $appPath/router/app.routes.ts
+command_msg $update "$appPath/router/app.routes.ts"
 sed -i "/export const APP_ROUTES: Routes.*/a { path: 'golden-layout', component: GoldenLayoutExamplePageComponent }," $appPath/router/app.routes.ts
+command_msg $update "$appPath/router/app.routes.ts"
 
 
 mkdir -p $projectPath/css/
 cp -r $basePath/templates/css/* $projectPath/css/
+command_msg $success "Golden layout css copy"
 mkdir -p $projectPath/img/
 cp -r $basePath/templates/img/* $projectPath/img/
+command_msg $success "Golden layout img copy"
 cp -r $basePath/templates/styles.scss $projectPath/styles.scss
+command_msg $update "$projectPath/styles.scss"
 
 sed -i "/^@NgModule.*/i import { GoldenLayoutExamplePageComponent } from './pages/golden-layout-example-page/golden-layout-example-page.component';" $appPath/app.module.ts
+command_msg $update "$appPath/app.module.ts"
 sed -i "/^@NgModule.*/i import { ColorComponent } from './components/golden-layout/color/color.component';" $appPath/app.module.ts
+command_msg $update "$appPath/app.module.ts"
 sed -i "/^@NgModule.*/i import { TextComponent } from './components/golden-layout/text/text.component';" $appPath/app.module.ts
+command_msg $update "$appPath/app.module.ts"
 sed -i "/^@NgModule.*/i import { BooleanComponent } from './components/golden-layout/boolean/boolean.component';" $appPath/app.module.ts
-
+command_msg $update "$appPath/app.module.ts"
 sed -i "/^@NgModule.*/i import { ControlsComponent } from './components/golden-layout/controls/controls.component';" $appPath/app.module.ts
+command_msg $update "$appPath/app.module.ts"
 sed -i "/^@NgModule.*/i import { GoldenLayoutHostComponent } from './components/golden-layout/golden-layout-host/golden-layout-host.component';" $appPath/app.module.ts
-
+command_msg $update "$appPath/app.module.ts"
 
 sed -i "/declarations.*/a GoldenLayoutExamplePageComponent," $appPath/app.module.ts
+command_msg $update "$appPath/app.module.ts"
 sed -i "/declarations.*/a ColorComponent," $appPath/app.module.ts
+command_msg $update "$appPath/app.module.ts"
 sed -i "/declarations.*/a TextComponent," $appPath/app.module.ts
+command_msg $update "$appPath/app.module.ts"
 sed -i "/declarations.*/a BooleanComponent," $appPath/app.module.ts
+command_msg $update "$appPath/app.module.ts"
 
 sed -i "/declarations.*/a ControlsComponent," $appPath/app.module.ts
+command_msg $update "$appPath/app.module.ts"
 sed -i "/declarations.*/a GoldenLayoutHostComponent," $appPath/app.module.ts
+command_msg $update "$appPath/app.module.ts"
 
 echo '<div><a routerLink="/golden-layout">Golden Layout</a></div>' >> $appPath/pages/landing-page/landing-page.component.html
+command_msg $update "$appPath/pages/landing-page/landing-page.component.html"
 
 
-echo "#################################"
-echo "$success: Golden Layout added to project $name"
-echo "#################################"
+echo -e "$success Golden Layout added to project $name"
+echo -e $line
diff --git a/scripts/add-mfe-project b/scripts/add-mfe-project
--- a/scripts/add-mfe-project
+++ b/scripts/add-mfe-project
@@ -1,30 +1,58 @@
 #!/bin/bash
 
+Color_Off='\033[0m'       # Text Reset
+# Regular Colors
+Red='\033[0;31m'          # Red
+Green='\033[0;32m'        # Green
+Blue='\033[0;34m'         # Blue
+Yellow='\033[0;33m'       # Yellow
+Purple='\033[0;35m'       # Purple
+
+remove="${Purple}DELETE${Color_Off}"
+success="${Green}SUCCESS${Color_Off}"
+create="${Green}CREATE${Color_Off}"
+update="${Green}UPDATE${Color_Off}"
+error="${Red}ERROR${Color_Off}"
+starting="${Yellow}STARTING${Color_Off}"
+line="${Yellow}#################################${Color_Off}"
+complete="${Yellow}COMPLETED${Color_Off}"
+
 empty="empty"
 name=$empty
 port=$empty
+workspace=$empty
 basePath="/workspace"
 success="SUCCESS"
 error="ERROR"
 starting="STARTING"
 
+command_msg(){
+  if [ $? == 0 ] ; then
+    echo -e "$1 $2"
+  else
+    echo -e "$error $2"
+    exit 1
+  fi
+}
+
 # display help message if -h is a commandline arg
 help_message() {
   if [[ $1 == "-h" ]]; then
-    echo "Usage new_mfe.sh -p {dev port} -n {project name} [options]";
+    echo "Usage add-mfe-project.sh -p {dev port} -w {workspace} -n {project name} [options]";
     echo "-n: Angular project name";
+    echo "-w: Angular workspace name workspace - hint: look at your lib {workspace}-lib"
     echo "-p: Module federation remote's port and angular dev port";
     echo "OPTIONS:"
     echo "-b Root of the angular mono-repo"
-    exit 0
+    exit 1
   fi
 }
 
 validate_name() {
   appPath=$1
   if [[ -f "$appPath/app.module.ts" ]]; then
-    echo "$error: Project with the same name already exists";
-    exit 0
+    echo -e "$error Project with the same name already exists";
+    exit 1
   fi
 }
 
@@ -34,23 +62,24 @@ validate_port() {
   testPort="$(grep "\"port\": $port" ./angular.json)"
   # use the grep result to wildcard compare on the requested port
   if [[ $testPort == *"$port"* ]]; then
-    echo "$error: A project already exists on this port";
-    exit 0
+    echo -e "$error A project already exists on this port";
+    exit 1
   fi
 }
 
 validate_args() {
-  if [[ $port == $empty ]] || [[ $name == $empty ]] ; then
-    echo "$error: Invalid arguments, please see help (-h)"
-    exit 0
+  if [[ $port == $empty ]] || [[ $name == $empty ]] || [[ $workspace == $empty ]] ; then
+    echo -e "$error Invalid arguments, please see help (-h)"
+    exit 1
   fi
 }
 
-while getopts n:p:b:h flag
+while getopts n:p:w:b:h flag
 do
     case "${flag}" in
         n) name=${OPTARG};;
         p) port=${OPTARG};;
+        w) workspace=${OPTARG};;
         b) basePath=${OPTARG};;
         h) help="-h";;
     esac
@@ -62,8 +91,8 @@ help_message $help
 validate_args
 
 if [[ ! -d $basePath ]]; then
-  echo "$error: Root of the angular mono-repo cannot be found ($basePath)"
-  exit 0
+  echo -e "$error Root of the angular mono-repo cannot be found ($basePath)"
+  exit 1
 fi
 
 # path for the new project relative to basePath
@@ -76,68 +105,31 @@ cd $basePath
 validate_name $appPath
 validate_port
 
-echo "#################################"
-echo "$starting: Create MFE project $name on port $port"
-echo "#################################"
+echo -e $line
+echo -e "$starting: Create MFE project $name on port $port"
 
 # Create mfe ng project with name provided
 ng generate application $name
-echo "$success: Project created"
+echo -e "$success Project created"
 # configure the new project as a module federation remote on the port provided
 ng add @angular-architects/module-federation --project $name --port $port --type remote
-echo "$success: Module Federation configured"
-# if the project has been successfully created lets customise it
-if [[ ! -f "$appPath/app.module.ts" ]]; then
-  echo "$error: Project $name could not be found";
-  exit 0;
-fi
+echo -e "$success Module Federation configured"
 
-# add material to the new projects app.modules
-sed -i "/^@NgModule.*/i import { MaterialModules } from '../../../../material.modules'" $appPath/app.module.ts
-sed -i "/imports.*/a MaterialModules," $appPath/app.module.ts
-echo "$success: app.module.ts configured for MaterialModules"
-# Add base layout and components
-ng generate component layouts/default-layout --project=$name
-cp $basePath/templates/default-layout.component.html $appPath/layouts/default-layout/default-layout.component.html
-ng generate component pages/not-found-page --project=$name
-ng generate component pages/landing-page --project=$name
-echo "$success: base layout and components created"
-# fix up the router
-# need to skip if router not added
-if [[ -f "$appPath/app-routing.module.ts" ]]; then
-  mkdir $appPath/router
-  rm $appPath/app-routing.module.ts
-  cp -a ./templates/router/app-routing.module.txt $appPath/router/app-routing.module.ts
-  cp -a ./templates/router/app.routes.txt $appPath/router/app.routes.ts
-  # fix the app component for routing
-  sed -i "s/app-routing.module/router\\/app-routing.module/" $appPath/app.module.ts
-  echo "$success: router configured"
-fi
-
-# added environment variables
-cp -a ./templates/environments $projectPath
-echo "$success: environments copied to project"
-# update angular.json with production fileReplacements for env
-updatedAngularJson="$(jq ".projects.$name.architect.build.configurations.production.fileReplacements += [{\"replace\": \"src/environments/environment.ts\",\"with\": \"src/environments/environment.prod.ts\"}]" ./angular.json)"
-echo -E "${updatedAngularJson}" > angular.json
-echo "$success: angular.json updated with production.fileReplacements for environments"
+./scripts/patch-existing-project -n $name -b $basePath
 
 # add serve and build scripts to package.json
-updatedPackageJson="$(jq ".scripts += {\"serve:$name\": \"ng serve $name -o\"}" ./package.json)"
-echo -E "${updatedPackageJson}" > ./package.json
-updatedPackageJson="$(jq ".scripts += {\"build:$name\": \"ng build $name\"}" ./package.json)"
-echo -E "${updatedPackageJson}" > ./package.json
-serverAll="$(jq ".scripts.serveAll" ./package.json) \"npm run serve:$name\""
-# jq 'del(.scripts.serveAll)' ./package.json
-# updatedPackageJson="$(jq ".scripts += {\"serveAll\": $serverAll}" ./package.json)"
-echo $serverAll
-# echo -E "${updatedPackageJson}" > ./package.json
-echo "$success: package.json updated"
+serveAll=$(jq ".scripts.serve" ./package.json | sed -e 's/^"//' -e 's/"$//' -e 's/\\//g')
+npmAddScript -k serve -v "$serveAll \"npm run serve:$name\"" -f
 
-if [[ -f "./Jenkinsfile"]]; then
-  sed -i "/def microFrontends.*/a \ \ \t\t\t\t\t\t\t\t\t\t $name" ./Jenkinsfile
-fi
+echo -e "$success package.json updated"
+
+# if [[ -f "./Jenkinsfile"]]; then
+#   sed -i "/def microFrontends.*/a \ \ \t\t\t\t\t\t\t\t\t\t $name" ./Jenkinsfile
+# fi
 
 ./scripts/add-formly-to-project -n $name -b $basePath -i n
 
-./scripts/add-gl-to-project -n $name -b $basePath -i n
+# ./scripts/add-gl-to-project -n $name -b $basePath -t r -w $workspace -i n
+
+echo -e "$success MFE project $name on port $port created"
+echo -e $line
diff --git a/scripts/mono-repo-project b/scripts/mono-repo-project
--- a/scripts/mono-repo-project
+++ b/scripts/mono-repo-project
@@ -1,10 +1,25 @@
 #!/bin/bash
+
+Color_Off='\033[0m'       # Text Reset
+# Regular Colors
+Red='\033[0;31m'          # Red
+Green='\033[0;32m'        # Green
+Blue='\033[0;34m'         # Blue
+Yellow='\033[0;33m'       # Yellow
+Purple='\033[0;35m'       # Purple
+
+remove="${Purple}DELETE${Color_Off}"
+success="${Green}SUCCESS${Color_Off}"
+create="${Green}CREATE${Color_Off}"
+update="${Green}UPDATE${Color_Off}"
+error="${Red}ERROR${Color_Off}"
+starting="${Yellow}STARTING${Color_Off}"
+line="${Yellow}#################################${Color_Off}"
+complete="${Yellow}COMPLETED${Color_Off}"
+
 ngVersion=15.2.8
 ngCli="@angular/cli"
 basePath="/workspace"
-success="SUCCESS"
-error="ERROR"
-starting="STARTING"
 
 # display help message if -h is a commandline arg
 help_message() {
@@ -13,14 +28,24 @@ help_message() {
     echo "-n: Angular workspace name";
     echo "OPTIONS:"
     echo "-b Root of the angular mono-repo"
-    exit 0
+    exit 1
   fi
 }
 
 validate_args() {
   if [[ $name == $empty ]] ; then
-    echo "$error: Invalid arguments, please see help (-h)"
-    exit 0
+    echo -e "$error Invalid arguments, please see help (-h)"
+    exit 1
+  fi
+}
+
+
+command_msg(){
+  if [ $? == 0 ] ; then
+    echo -e "$1 $2"
+  else
+    echo -e "$error $2"
+    exit 1
   fi
 }
 
@@ -38,78 +63,100 @@ help_message $help
 
 validate_args
 
-echo "#################################"
-echo "$starting: Creating $name"
-echo "#################################"
+echo -e $line
+echo -e "$starting: Creating $name"
 
 # as angular is difficult with dependency management, ensure legacy-peer-deps is set
 
 if [[ ! -d $basePath ]]; then
-  echo "$error: Root of the angular mono-repo cannot be found ($basePath)"
-  exit 0
+  echo -e "$error Root of the angular mono-repo cannot be found ($basePath)"
+  exit 1
 fi
 
 cd $basePath
 
-projectPath="./projects/$name/src";
+projectPath="./projects/$name/src"
 appPath="$projectPath/app"
 
+
 cp ./templates/material.modules.ts $basePath
-echo "$success: material.modules copied"
+command_msg $create "material.modules.ts"
+
 rm .gitignore
 ng new $name --no-create-application --directory ./ --skip-install
-echo "$success: workspace $name created"
+command_msg $success "workspace $name created"
 ng generate library $name-lib --skip-install
-echo "$success: library $name-lib created"
+command_msg $success "library $name-lib created"
 
 ./scripts/patch-existing-lib -n $name-lib -b $basePath
-echo "$success: library $name-lib patched"
 
 mkdir -p ./projects/$name-lib/src/lib/golden-layout
 cp $basePath/templates/base-component.directive ./projects/$name-lib/src/lib/golden-layout/base-component.directive.ts
+command_msg $create "projects/$name-lib/src/lib/golden-layout/base-component.directive.ts"
 cp $basePath/templates/text-component.interface ./projects/$name-lib/src/lib/golden-layout/text-component.interface.ts
-echo "$success: golden layout directive add to $name-lib"
+command_msg $create "projects/$name-lib/src/lib/golden-layout/text-component.interface.ts"
+
+
 echo "export * from './lib/golden-layout/base-component.directive';" >> ./projects/$name-lib/src/public-api.ts
+command_msg $update "projects/$name-lib/src/public-api.ts"
 echo "export * from './lib/golden-layout/text-component.interface';" >> ./projects/$name-lib/src/public-api.ts
+command_msg $update "projects/$name-lib/src/public-api.ts"
 
 sed -i "/^@NgModule.*/i import { BaseComponentDirective } from './golden-layout/base-component.directive';" ./projects/$name-lib/src/lib/$name-lib.module.ts
+command_msg $update "projects/$name-lib/src/lib/$name-lib.module.ts"
 sed -i "/exports.*/a BaseComponentDirective," ./projects/$name-lib/src/lib/$name-lib.module.ts
+command_msg $update "projects/$name-lib/src/lib/$name-lib.module.ts"
 sed -i "/declarations.*/a BaseComponentDirective," ./projects/$name-lib/src/lib/$name-lib.module.ts
+command_msg $update "projects/$name-lib/src/lib/$name-lib.module.ts"
 
-echo "$starting: create project shell"
+echo -e "$starting: create project shell"
 ng generate application shell --skip-install
-echo "$success: project shell created"
+command_msg $success "project shell created"
+npm install -g npm-add-script
+command_msg $success "npm npm-add-script added"
+
 ./scripts/patch-existing-project -n shell -b $basePath
-echo "$success: project shell patched"
 
 ng add @angular/material --project shell
-echo "$success: angular/material added"
+command_msg $success "angular/material added to project shell"
 
 ng add @angular-architects/module-federation --project shell --port 4200 --type dynamic-host
+command_msg $success "Module federation added to shell project"
+
 mkdir -p ./projects/shell/src/app/components/module-federation
 cp -r $basePath/templates/module-federation/* ./projects/shell/src/app/components/module-federation
+command_msg $create "Module federation service added to projects/shell/src/app/components/module-federation"
 mkdir -p ./projects/shell/src/assets
 cp $basePath/templates/mf.manifest.json ./projects/shell/src/assets/mf.manifest.json
-echo "$success: Module federation configured for shell project"
+command_msg $create "projects/shell/src/assets/mf.manifest.json"
+echo -e "$success Module federation configured for shell project"
 
+mfReattemp=0
 # Sometimes module-federation isn't being installed. Lets force it
-if ! (grep -q '"@angular-architects/module-federation":' ./package.json)
-then
- ng add @angular-architects/module-federation --project shell --port 4200 --type dynamic-host
+until (grep -q '"@angular-architects/module-federation":' ./package.json)
+do
+  mfReattemp=1
+  echo -e "${Yellow}REATTEMPT${Color_Off} detected module federation missing, trying to add"
+  ng add @angular-architects/module-federation --project shell --port 4200 --type dynamic-host
+done
+
+if [[ $mfReattempt == 1 ]]; then
+  echo -e "$success Module federation reattempt"
 fi
 
 ./scripts/add-formly-to-project -n shell -b $basePath -i y
-./scripts/add-gl-to-project -n shell -b $basePath -w $name -i y
+./scripts/add-gl-to-project -n shell -b $basePath -w $name -t s -i y
 
 cp $basePath/templates/app.component.html $basePath/projects/shell/src/app/app.component.html
+command_msg $update "projects/shell/src/app/app.component.html"
 
-npm install -g npm-add-script
 npmAddScript -k serve -v "concurrently --kill-others \"npm run watch:$name-lib\" \"npm run serve:shell\"" -f
+command_msg $update "project.json"
 
 npm i concurrently --save-dev
+command_msg $success "npm concurrently added"
 npm install
 
-echo "#################################"
-echo "$success: Creating workspace $name complete"
-echo "#################################"
+echo -e "$success Creating workspace $name complete"
+echo -e $line
 
diff --git a/scripts/new-formly-component b/scripts/new-formly-component
--- a/scripts/new-formly-component
+++ b/scripts/new-formly-component
@@ -1,30 +1,53 @@
 #!/bin/bash
 
+Color_Off='\033[0m'       # Text Reset
+# Regular Colors
+Red='\033[0;31m'          # Red
+Green='\033[0;32m'        # Green
+Blue='\033[0;34m'         # Blue
+Yellow='\033[0;33m'       # Yellow
+Purple='\033[0;35m'       # Purple
+
+remove="${Purple}DELETE${Color_Off}"
+success="${Green}SUCCESS${Color_Off}"
+create="${Green}CREATE${Color_Off}"
+update="${Green}UPDATE${Color_Off}"
+error="${Red}ERROR${Color_Off}"
+starting="${Yellow}STARTING${Color_Off}"
+line="${Yellow}#################################${Color_Off}"
+complete="${Yellow}COMPLETED${Color_Off}"
+
 empty="empty"
 name=$empty
 project=$empty
 customTypeSelection="y"
 basePath="/workspace"
-success="SUCCESS"
-error="ERROR"
-starting="STARTING"
+
+command_msg(){
+  if [ $? == 0 ] ; then
+    echo -e "$1 $2"
+  else
+    echo -e "$error $2"
+    exit 1
+  fi
+}
 
 help_message() {
   if [[ $1 == "-h" ]]; then
-    echo "Usage new_mfe.sh -p {dev port} -n {project name} [options]";
+    echo "Usage add-formly-component.sh -n {component-name} -p {project name} [options]";
     echo "-n: Component name in (kebab-case)"
     echo "-p: Angular project name";
     echo "OPTIONS:"
     echo "-c Register as formly custom type? Y|n"
     echo "-b Root of the angular mono-repo"
-    exit 0
+    exit 1
   fi
 }
 
 validate_args() {
   if [[ $name == $empty || $project == $empty ]] ; then
-    echo "$error: Invalid arguments, please see help (-h)"
-    exit 0
+    echo -e "$error Invalid arguments, please see help (-h)"
+    exit 1
   fi
 }
 
@@ -44,13 +67,12 @@ help_message $help
 
 validate_args
 
-echo "#################################"
-echo "$starting: Creating formly component $name"
-echo "#################################"
+echo -e $line
+echo -e "$starting Creating formly component $name"
 
 if [[ ! -d $basePath ]]; then
-  echo "$error: Root of the angular mono-repo cannot be found ($basePath)"
-  exit 0
+  echo -e "$error Root of the angular mono-repo cannot be found ($basePath)"
+  exit 1
 fi
 
 cd $basePath
@@ -62,19 +84,22 @@ componentName="${echo $name | sed -e "s/\b\(.\)/\u\1/g" | sed -e 's/-//g'}Compon
 componentPath="./components/formly/$name/$name.component"
 
 ng generate component components/formly/${name} --project=$project
-echo "$success: $name component generated"
+echo -e "$success $name component generated"
 
 sed -i "/^@NgModule.*/i import { $componentName } from '$componentPath';" $appPath/app.module.ts
 sed -i "/declarations.*/a $componentName," $appPath/app.module.ts
 
-echo "$success: component $name registered within app.module.ts"
+echo -e "$success component $name registered within app.module.ts"
 
 if [[ $customTypeSelection == "y" || $customTypeSelection == "Y" ]]; then
     customType="{ name: $name, component: $componentName, wrappers: [] },"
     # look for //formly-types in app.module.ts and insert the new formly type above
     sed -i "/] //formly-types.*/i $customType" $appPath/app.module.ts
 
-    echo "$success: formly custom type added to app.module.ts"
+    echo -e "$success formly custom type added to app.module.ts"
 fi
+
+echo -e "$success Formly component $name created"
+echo -e $line
 
 
diff --git a/scripts/new-gl-component b/scripts/new-gl-component
--- a/scripts/new-gl-component
+++ b/scripts/new-gl-component
@@ -1,35 +1,61 @@
 #!/bin/bash
 
+Color_Off='\033[0m'       # Text Reset
+# Regular Colors
+Red='\033[0;31m'          # Red
+Green='\033[0;32m'        # Green
+Blue='\033[0;34m'         # Blue
+Yellow='\033[0;33m'       # Yellow
+Purple='\033[0;35m'       # Purple
+
+remove="${Purple}DELETE${Color_Off}"
+success="${Green}SUCCESS${Color_Off}"
+create="${Green}CREATE${Color_Off}"
+update="${Green}UPDATE${Color_Off}"
+error="${Red}ERROR${Color_Off}"
+starting="${Yellow}STARTING${Color_Off}"
+line="${Yellow}#################################${Color_Off}"
+complete="${Yellow}COMPLETED${Color_Off}"
+
 empty="empty"
 name=$empty
 workspace=$empty
+project=$empty
 basePath="/workspace"
-success="SUCCESS"
-error="ERROR"
-starting="STARTING"
+
+command_msg(){
+  if [ $? == 0 ] ; then
+    echo -e "$1 $2"
+  else
+    echo -e "$error $2"
+    exit 1
+  fi
+}
 
 help_message() {
   if [[ $1 == "-h" ]]; then
-    echo "Usage new_mfe.sh -p {dev port} -n {project name} [options]";
+    echo "Usage new-gl-component.sh -n {component-name} -p {project name} -w {workspace} [options]";
     echo "-n: Component name in (kebab-case)"
+    echo "-p: Angular project name"
     echo "-w: Angular workspace name";
     echo "OPTIONS:"
     echo "-b Root of the angular mono-repo"
-    exit 0
+    exit 1
   fi
 }
 
 validate_args() {
-  if [[ $name == $empty || $workspace == $empty ]] ; then
-    echo "$error: Invalid arguments, please see help (-h)"
-    exit 0
+  if [[ $name == $empty || $workspace == $empty || $project == $empty ]] ; then
+    echo -e "$error Invalid arguments, please see help (-h)"
+    exit 1
   fi
 }
 
-while getopts n:w:b:h flag
+while getopts n:p:w:b:h flag
 do
     case "${flag}" in
         n) name=${OPTARG};;
+        p) project=${OPTARG};;
         w) workspace=${OPTARG};;
         b) basePath=${OPTARG};;
         h) help="-h";;
@@ -41,14 +67,12 @@ help_message $help
 
 validate_args
 
-echo "#################################"
-echo "$starting: Creating Golden Layout Component $name"
-echo "#################################"
-
+echo -e $line
+echo -e "$starting Creating Golden Layout Component $name"
 
 if [[ ! -d $basePath ]]; then
-  echo "$error: Root of the angular mono-repo cannot be found ($basePath)"
-  exit 0
+  echo -e "$error Root of the angular mono-repo cannot be found ($basePath)"
+  exit 1
 fi
 
 cd $basePath
@@ -60,12 +84,12 @@ componentName="${echo $name | sed -e "s/\b\(.\)/\u\1/g" | sed -e 's/-//g'}Compon
 componentPath="./components/golden-layout/$name/$name.component"
 
 ng generate component components/golden-layout/${name} --project=$project
-echo "$success: $name component generated"
+echo -e "$success $name component generated"
 
 sed -i "/^@NgModule.*/i import { $componentName } from '$componentPath';" $appPath/app.module.ts
 sed -i "/declarations.*/a $componentName," $appPath/app.module.ts
 
-echo "$success: component $name registered within app.module.ts"
+echo -e "$success component $name registered within app.module.ts"
 
 cp $basePath/templates/gl.component ${componentPath}.ts
 cp $basePath/templates/gl.component.html ${componentPath}.html
@@ -73,5 +97,8 @@ cp $basePath/templates/gl.component.html ${componentPath}.html
 sed -i "s/{workspace}/$workspace/g" ${componentPath}.ts
 sed -i "s/{name}/$name/g" ${componentPath}.ts
 sed -i "s/{componentName}/$componentName/g" ${componentPath}.ts
+
+echo -e "$success Golden Layout Component $name created"
+echo -e $line
 
 
diff --git a/scripts/patch-existing-lib b/scripts/patch-existing-lib
--- a/scripts/patch-existing-lib
+++ b/scripts/patch-existing-lib
@@ -1,27 +1,50 @@
 #!/bin/bash
 
+Color_Off='\033[0m'       # Text Reset
+# Regular Colors
+Red='\033[0;31m'          # Red
+Green='\033[0;32m'        # Green
+Blue='\033[0;34m'         # Blue
+Yellow='\033[0;33m'       # Yellow
+Purple='\033[0;35m'       # Purple
+
+remove="${Purple}DELETE${Color_Off}"
+success="${Green}SUCCESS${Color_Off}"
+create="${Green}CREATE${Color_Off}"
+update="${Green}UPDATE${Color_Off}"
+error="${Red}ERROR${Color_Off}"
+starting="${Yellow}STARTING${Color_Off}"
+line="${Yellow}#################################${Color_Off}"
+complete="${Yellow}COMPLETED${Color_Off}"
+
 empty="empty"
-project=$empty
+name=$empty
 basePath="/workspace"
-success="SUCCESS"
-error="ERROR"
-starting="STARTING"
+
+command_msg(){
+  if [ $? == 0 ] ; then
+    echo -e "$1 $2"
+  else
+    echo -e "$error $2"
+    exit 1
+  fi
+}
 
 # display help message if -h is a commandline arg
 help_message() {
   if [[ $1 == "-h" ]]; then
-    echo "Usage add-environments.sh -p {project name}";
+    echo "Usage patch-existing-lib.sh -n {project name}";
     echo "-n: Angular project to add environments to";
     echo "OPTIONS:"
     echo "-b Root of the angular mono-repo"
-    exit 0
+    exit 1
   fi
 }
 
 while getopts n:b:h flag
 do
     case "${flag}" in
-        n) project=${OPTARG};;
+        n) name=${OPTARG};;
         b) basePath=${OPTARG};;
         h) help="-h";;
     esac
@@ -29,9 +52,13 @@ done
 
 cd $basePath
 
+echo -e $line
+echo -e "$starting Patching library $name"
+
 # add build scripts to package.json
-updatedPackageJson="$(jq ".scripts += {\"watch:$project\": \"ng build $project --watch\"}" ./package.json)"
-echo -E "${updatedPackageJson}" > ./package.json
-updatedPackageJson="$(jq ".scripts += {\"build:$project\": \"ng build $project\"}" ./package.json)"
-echo -E "${updatedPackageJson}" > ./package.json
-echo "$success: package.json updated"
+npmAddScript -k "watch:$name" -v "ng build $name --watch" -f
+npmAddScript -k "build:$name" -v "ng build $name" -f
+command_msg $update "package.json"
+
+echo -e "$success Library $name patched"
+echo -e $line
diff --git a/scripts/patch-existing-project b/scripts/patch-existing-project
--- a/scripts/patch-existing-project
+++ b/scripts/patch-existing-project
@@ -1,20 +1,44 @@
 #!/bin/bash
 
+Color_Off='\033[0m'       # Text Reset
+# Regular Colors
+Red='\033[0;31m'          # Red
+Green='\033[0;32m'        # Green
+Blue='\033[0;34m'         # Blue
+Yellow='\033[0;33m'       # Yellow
+Purple='\033[0;35m'       # Purple
+
+remove="${Purple}DELETE${Color_Off}"
+success="${Green}SUCCESS${Color_Off}"
+create="${Green}CREATE${Color_Off}"
+update="${Green}UPDATE${Color_Off}"
+error="${Red}ERROR${Color_Off}"
+starting="${Yellow}STARTING${Color_Off}"
+complete="${Yellow}COMPLETED${Color_Off}"
+line="${Yellow}#################################${Color_Off}"
+complete="${Yellow}COMPLETED${Color_Off}"
+
 empty="empty"
 name=$empty
 basePath="/workspace"
-success="SUCCESS"
-error="ERROR"
-starting="STARTING"
+
+command_msg(){
+  if [ $? == 0 ] ; then
+    echo -e "$1 $2"
+  else
+    echo -e "$error $2"
+    exit 1
+  fi
+}
 
 # display help message if -h is a commandline arg
 help_message() {
   if [[ $1 == "-h" ]]; then
-    echo "Usage fix-existing-project.sh -p {project name}";
+    echo "Usage patch-existing-project.sh -n {project name}";
     echo "-n: Angular project to add environments to";
     echo "OPTIONS:"
     echo "-b Root of the angular mono-repo"
-    exit 0
+    exit 1
   fi
 }
 
@@ -31,8 +55,8 @@ done
 help_message $help
 
 if [[ ! -d $basePath ]]; then
-  echo "$error: Root of the angular mono-repo cannot be found ($basePath)"
-  exit 0
+  echo -e "$error Root of the angular mono-repo cannot be found ($basePath)"
+  exit 1
 fi
 
 cd $basePath
@@ -40,51 +64,60 @@ cd $basePath
 projectPath="./projects/$name/src";
 appPath="$projectPath/app"
 
-echo "#################################"
-echo "$starting: Updating project $name"
-echo "#################################"
+echo -e $line
+echo -e "$starting Patching project $name"
 
 # if the project has been successfully created lets customise it
 if [[ ! -f "$appPath/app.module.ts" ]]; then
-  echo "$error: Project $name could not be found";
-  exit 0;
+  echo -e "$error Project $name could not be found";
+  exit 1;
 fi
 
 # add material to the new projects app.modules
 sed -i "/^@NgModule.*/i import { MaterialModules } from '../../../../material.modules'" $appPath/app.module.ts
 sed -i "/imports.*/a MaterialModules," $appPath/app.module.ts
-echo "$success: app.module.ts configured for MaterialModules"
+command_msg $update "$appPath/app.module.ts"
 
 # Add base layout and components
 ng generate component layouts/default-layout --project=$name
+command_msg $success "component layouts/default-layout in project $name"
 cp $basePath/templates/default-layout.component.html $appPath/layouts/default-layout/default-layout.component.html
+command_msg $update "$appPath/layouts/default-layout/default-layout.component.html"
 ng generate component pages/not-found-page --project=$name
+command_msg $success "component pages/not-found-page in project $name"
 ng generate component pages/landing-page --project=$name
-echo "$success: base layout and components created"
+command_msg $success "component pages/landing-page in project $name"
+
 
 # fix up the router
 # need to skip if router not added
 if [[ -f "$appPath/app-routing.module.ts" ]]; then
   mkdir $appPath/router
   rm $appPath/app-routing.module.ts
+  command_msg $remove "$appPath/app-routing.module.ts"
   cp -a ./templates/router/app-routing.module.txt $appPath/router/app-routing.module.ts
+  command_msg $create "$appPath/router/app-routing.module.ts"
   cp -a ./templates/router/app.routes.txt $appPath/router/app.routes.ts
+  command_msg $create "$appPath/router/app.routes.ts"
   # fix the app component for routing
   sed -i "s/app-routing.module/router\\/app-routing.module/" $appPath/app.module.ts
-  echo "$success: router configured"
+  command_msg $update "$appPath/app.module.ts"
+  echo -e "$success router configured"
 fi
 
 # added environment variables
 cp -a ./templates/environments $projectPath
-echo "$success: environments copied to project"
+command_msg $success "environments copied to project $name"
 # update angular.json with production fileReplacements for env
 updatedAngularJson="$(jq ".projects.$name.architect.build.configurations.production.fileReplacements += [{\"replace\": \"src/environments/environment.ts\",\"with\": \"src/environments/environment.prod.ts\"}]" ./angular.json)"
 echo -E "${updatedAngularJson}" > ./angular.json
-echo "$success: angular.json updated with production.fileReplacements for environments"
+command_msg $update "angular.json"
+echo -e "$success angular.json updated with production.fileReplacements for environments"
 
 # added serve a build to package json
-updatedPackageJson="$(jq ".scripts += {\"serve:$name\": \"ng serve $name -o\"}" ./package.json)"
-echo -E "${updatedPackageJson}" > ./package.json
-updatedPackageJson="$(jq ".scripts += {\"build:$name\": \"ng build $name\"}" ./package.json)"
-echo -E "${updatedPackageJson}" > ./package.json
-echo "$success: package.json updated"
+npmAddScript -k "serve:$name" -v "ng serve $name -o" -f
+npmAddScript -k "build:$name" -v "ng build $name" -f
+command_msg $update "package.json"
+
+echo -e "$complete Project $name patched"
+echo -e $line
